export const AUTH = "AUTH";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const CHECK_AUTH = "CHECK_AUTH";
export const CLEAR_AUTH = "CLEAR_AUTH";
export const LOGOUT = "LOGOUT";

export const GET_USERS_INFO = "GET_USERS_INFO";
export const GET_USERS_INFO_START = "GET_USERS_INFO_START"; 
export const GET_USERS_INFO_SUCCESS = "GET_USERS_INFO_SUCCESS";
export const GET_USERS_INFO_FAIL = "GET_USERS_INFO_FAIL"

export const GET_SEARCH_DETAILS = 'GET_SEARCH_DETAILS'
export const GET_SEARCH_DETAILS_START = 'GET_SEARCH_DETAILS_START'
export const GET_SEARCH_DETAILS_DONE = 'GET_SEARCH_DETAILS_DONE'

export const GET_NEWS_FEED = 'GET_NEWS_FEED'
export const GET_NEWS_FEED_START = 'GET_NEWS_FEED_START'
export const GET_NEWS_FEED_SUCCESS = 'GET_NEWS_FEED_SUCCESS'
export const GET_NEWS_FEED_FAIL = 'GET_NEWS_FEED_FAIL'

export const DISMISS_AUTH_ERROR = "DISMISS_AUTH_ERROR"; 
export const DISMISS_NEWS_ERROR = "DISMISS_NEWS_ERROR"; 
